# Generated by Django 6.0.6 on 2026-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.PositiveIntegerField(),
        ),
    ]
