# Generated by Django 6.0.6 on 2026-06-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_category_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
