# Generated by Django 6.0.6 on 2026-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "price_per_night",
                    models.PositiveIntegerField(
                        help_text="Price per night in KRW", verbose_name="Price"
                    ),
                ),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=140)),
                (
                    "pet_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Is pet allowed in this house?",
                        verbose_name="Pet Allowed?",
                    ),
                ),
            ],
        ),
    ]
