# Generated by Django 6.0.6 on 2026-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_rename_price_house_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="pet_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
