# Generated by Django 5.0.6 on 2024-07-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_host_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
